fineract:
  api:
    url: https://localhost:443/fineract-provider/api/v1
    tenant: default
    username: mifos
    password: password
    # Configurable locale and date format
    locale: en
    dateFormat: dd MMMM yyyy

keycloak:
  # Authorization endpoint for getting the code
  auth-url: http://172.17.0.1:9000/realms/fineract/protocol/openid-connect/auth
  # Token endpoint for exchanging code for access token
  token-url: http://172.17.0.1:9000/realms/fineract/protocol/openid-connect/token
  grant-type: authorization_code
  client-id: community-app
  client-secret: "**********"
  redirect-uri: http://localhost:8081/callback
  scope: openid profile email
  # PKCE configuration (recommended for security)
  use-pkce: true

# RestTemplate configuration
rest:
  connection:
    timeout: 30000  # Connection timeout in milliseconds (30 seconds)
  read:
    timeout: 60000  # Read timeout in milliseconds (60 seconds)

# Retry configuration
retry:
  max-attempts: 3
  initial-interval: 1000  # Initial backoff interval in milliseconds
  multiplier: 2.0  # Backoff multiplier
  max-interval: 10000  # Maximum backoff interval in milliseconds

# Authorization code flow configuration
auth:
  # How long to wait for user to complete authorization (in seconds)
  timeout: 300
  # Port for the local callback server (different from Spring Boot port)
  callback-port: 8081
  # Port range to try if primary port is busy
  callback-port-range: 8081-8090