fineract:
  api:
    url: https://localhost/fineract-provider/api/v1
    tenant: default

    # Authentication configuration - must be one of: 'oauth' or 'basic'
    auth:
      type: ${AUTH_TYPE:oauth}  # Set to 'basic' or 'oauth' (default: oauth)

      # Basic Auth configuration (used when auth.type=basic)
      basic:
        username: mifos
        password: password

      # OAuth configuration (used when auth.type=oauth)
      oauth:
        keycloak:
          url: http://172.17.0.1:9000/realms/fineract/protocol/openid-connect/token
          grant-type: password
          client-id: setup-app-client
          client-secret: '**********'
          username: ${fineract.api.auth.basic.username}
          password: ${fineract.api.auth.basic.password}

    # Configurable locale and date format
    locale: en
    dateFormat: dd MMMM yyyy

# RestTemplate configuration
rest:
  connection:
    timeout: 30000  # Connection timeout in milliseconds (30 seconds)
  read:
    timeout: 60000  # Read timeout in milliseconds (60 seconds)

# Retry configuration
retry:
  max-attempts: 3
  initial-interval: 1000  # Initial backoff interval in milliseconds
  multiplier: 2.0  # Backoff multiplier
  max-interval: 10000  # Maximum backoff interval in milliseconds
